### ISSUE TITLE
Epic: Disk cloning

### ISSUE THREAD

**Issue by ArseniiPetrovich** [protofire/Filecoin-node-hosting-management#15]
- [x] #11 Upgrade EKS to 1.17
- [x] #12 Install AWS EBS CSI Driver 
- [x] #13 Automate snapshot taking
- [x] #14 Automate disk creation from snapshot
- [ ] Monitor AWS EBS CSI Driver for disk cloning feature
