### ISSUE TITLE
Epic: Autobuild lotus image with notifications

### ISSUE THREAD

**Issue by symanovich-a** [protofire/Filecoin-node-hosting-management#18]
- [x] #9 Configure auto build docker images in docker hub

- [x] #17 Track tag creation in lotus repository with changes in lotus-docker repository

- [x] #16 Lotus image build notification
