### ISSUE TITLE
Epic: Create monitoring system

### ISSUE THREAD

**Issue by ArseniiPetrovich** [protofire/Filecoin-node-hosting-management#4]
- [ ] Write polling system for Prometheus (#3)
- [ ] Write dashboards at Grafana (#2)
- [ ] Write alerts at Alertmanager (#1)
